#!/bin/bash
source /usr/lib/openfoam/openfoam2212/etc/bashrc
export OMPI_MCA_btl_vader_single_copy_mechanism=none

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Remove surface and features
rm -rf constant/triSurface/*.eMesh
rm -rf constant/extendedFeatureEdgeMesh

#------------------------------------------------------------------------------
